version: '3.8'

services:
  arbnb-django:
    build: .
    command: gunicorn arbnb.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=arbnb.settings
    expose:
      - 8000
    depends_on:
      - ldap
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - arbnb-django
    restart: unless-stopped

  ldap:
    image: osixia/openldap:1.5.0
    container_name: ldap
    environment:
      - LDAP_ORGANISATION=MiEmpresa
      - LDAP_DOMAIN=andres.work.gd
      - LDAP_ADMIN_PASSWORD=admin
      - LDAP_TLS=false
      - LDAP_REMOVE_CONFIG_AFTER_SETUP=false
    ports:
      - "389:389"
    volumes:
      - ./ldap-data:/var/lib/ldap
      - ./ldap-config:/etc/ldap/slapd.d
    restart: unless-stopped

  phpldapadmin:
    image: osixia/phpldapadmin:0.9.0
    container_name: phpldapadmin
    environment:
      - PHPLDAPADMIN_LDAP_HOSTS=ldap
      - PHPLDAPADMIN_HTTPS=false
    ports:
      - "6443:80"
    depends_on:
      - ldap
    restart: unless-stopped
