version: '3.8'

services:
  django:
    build: .
    command: gunicorn arbnb.wsgi:application --bind 0.0.0.0:8000
    env_file:
      - .env    # <--- Añadido para que Docker Compose cargue las variables desde el archivo .env
    environment:
      - DJANGO_SETTINGS_MODULE=arbnb.settings
    expose:
      - 8000
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - django
    restart: unless-stopped
