version: '3.8'

services:
  django:
    build: .
    command: >
      sh -c "python manage.py migrate && gunicorn arbnb.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
      - ./db/db.sqlite3:/app/db/db.sqlite3
    expose:
      - 8000
    environment:
      - DJANGO_SETTINGS_MODULE=arbnb.settings

  nginx:
    image: nginx:latest
    ports:
      - "8000:80"  # Expone el nginx en el puerto 8000 de tu máquina
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - django
