apiVersion: apps/v1
kind: Deployment
metadata:
  name: arbnb-django-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arbnb-django
  template:
    metadata:
      labels:
        app: arbnb-django
    spec:
      containers:
      - name: arbnb-django
        image: arbnb-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
