apiVersion: apps/v1
kind: Deployment
metadata:
  name: arbnb-nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arbnb-nginx
  template:
    metadata:
      labels:
        app: arbnb-nginx
    spec:
      containers:
      - name: arbnb-nginx
        image: nginx:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-config
