apiVersion: apps/v1
kind: Deployment
metadata:
  name: arbnb-django-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arbnb-django
  template:
    metadata:
      labels:
        app: arbnb-django
    spec:
      containers:
      - name: arbnb-django
        image: andresnenis/arbnb-django:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: arbnb.settings
        - name: AUTH_LDAP_SERVER_URI
          value: ldap://ldap-service