apiVersion: apps/v1
kind: Deployment
metadata:
  name: arbnb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: arbnb-app
  template:
    metadata:
      labels:
        app: arbnb-app
    spec:
      containers:
      - name: arbnb-arbnb-app
        image: arbnb-arbnb-app
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: arbnb.settings  # Ajusta según tu configuración
