apiVersion: apps/v1
kind: Deployment
metadata:
  name: ldap-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ldap
  template:
    metadata:
      labels:
        app: ldap
    spec:
      containers:
      - name: ldap
        image: osixia/openldap:1.5.0
        ports:
        - containerPort: 389
        env:
        - name: LDAP_ORGANISATION
          value: "MiEmpresa"
        - name: LDAP_DOMAIN
          value: "andres.work.gd"
        - name: LDAP_ADMIN_PASSWORD
          value: "admin"
        - name: LDAP_TLS
          value: "false"