apiVersion: v1
kind: Service
metadata:
  name: arbnb-service
spec:
  type: NodePort
  selector:
    app: arbnb-app
  ports:
    - protocol: TCP
      port: 8000          # Puerto dentro del clúster
      targetPort: 8000    # Puerto del contenedor
      nodePort: 30080     # Puerto accesible desde fuera (puedes cambiarlo si quieres)
