# Generated by Django 3.2.12 on 2025-02-25 16:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alojamientos_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='alquiler',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alojamiento',
            name='alquileres',
            field=models.ManyToManyField(related_name='alquileres', through='alojamientos_app.Alquiler', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alojamiento',
            name='propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='propietario', to=settings.AUTH_USER_MODEL),
        ),
    ]
