# Generated by Django 5.1.7 on 2025-05-22 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alojamientos_app', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquiler',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
